[routers]
10.16.0.1
10.48.0.1



[routers:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_rsa 
ansible_port=8822
#ansible_ssh_extra_args='-o PubkeyAcceptedAlgorithms=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa'
#ansible_ssh_common_args='-o PubkeyAcceptedAlgorithms=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa'
ansible_network_os=routeros
#
#ansible_libssh_macs="hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,ssh-dss,ssh-rsa"
#ansible_network_cli_libssh_macs="hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,ssh-dss,ssh-rsa"
