- name: Write kernel version to file
  hosts:
#    - routers1
#    - routers2
#    - CAPsMANs
#    - switches1
#    - switches2
    - WiFi1
    - WiFi2
  gather_facts: false
  vars:
    logfile: "/tmp/mikrotiks_log"
    loghost: "localhost"
  tasks:
    - name: Gather facts
      community.routeros.api_facts:
        hostname: "{{ inventory_hostname }}"
        password: "{{ ansible_password }}"
        username: "{{ ansible_user }}"
        timeout: 60
        gather_subset:
          - default
          - hardware
    - name: Write info to file
      lineinfile:
        create: true
        state: present
        path: "{{ logfile }}"
        line: '{{inventory_hostname}};{{ ansible_facts["net_hostname"] }};{{ansible_facts["net_model"]}};{{ ansible_facts["net_version"] }};'
        regexp: '^{{ ansible_facts["net_hostname"] }}[[;]].*'
#        line: '{{inventory_hostname}} {{ ansible_facts["net_hostname"] }} {{ansible_facts["net_model"]}} {{ ansible_facts["net_version"] }}'
#        regexp: '^{{ ansible_facts["net_hostname"] }}[[:space:]].*'
      delegate_to: "{{ loghost }}"
