- name: Upload file to router
  hosts: 10.22.3.1
#  hosts: all
  gather_facts: false
  tasks:
    - name: file 1 upload
      net_put:
        src: ./files/UpdateRouterOS.txt
        dest: ./UpdateRouterOS.txt
        protocol: sftp
    - name: file 2 upload
      net_put:
        src: ./files/UpgradeFirmware.txt
        dest: ./UpgradeFirmware.txt
        protocol: sftp
    - name: file 3 upload
      net_put:
        src: ./files/UpgradeAllowed
        dest: ./UpgradeAllowed
        protocol: sftp
    - name: Create scripts
      routeros_command:
        commands: 
          - /system script add name=UpdateRouterOS source=[/file get UpdateRouterOS.txt contents]
          - /system script add name=UpgradeFirmware source=[/file get UpgradeFirmware.txt contents]
    - name: File demonstate after
      routeros_command:
        commands: /file print
      register: file_after
    - name: debug print after
      debug: var=file_after.stdout_lines
