- name: Upload file to router
  hosts: 
    - routers2
  gather_facts: false
  tasks:
    - name: file UpdateRouterOS.txt upload
      net_put:
        src: ./files/UpdateRouterOS.txt
        dest: ./UpdateRouterOS.txt
        protocol: sftp
    - name: file UpgradeFirmware.txt upload
      net_put:
        src: ./files/UpgradeFirmware.txt
        dest: ./UpgradeFirmware.txt
        protocol: sftp
    - name: file UpgradeAllowed upload
      net_put:
        src: ./files/UpgradeAllowed
        dest: ./UpgradeAllowed
        protocol: sftp
    - name: Create scripts
      routeros_command:
        commands: 
          - /system script add name=UpdateRouterOS source=[/file get UpdateRouterOS.txt contents]
          - /system script add name=UpgradeFirmware source=[/file get UpgradeFirmware.txt contents]
    - name: Create tasks in Scheduler
      routeros_command:
        commands: 
          - /system scheduler add name="daily_UpdateRouterOS"  start-time=03:00:00 interval=1d on-event="UpdateRouterOS"
          - /system scheduler add name="daily_UpgradeFirmware" start-time=03:30:00 interval=1d on-event="UpgradeFirmware"
#    - name: File list after
#      routeros_command:
#        commands: /file print
#      register: file_after
#    - name: debug print after
#      debug: var=file_after.stdout_lines
